### ISSUE TITLE
Results are missing vs "bower search"

### ISSUE THREAD

**Issue by sheerun** [bower/search#36]
See: https://github.com/bower/bower/issues/1270

```
test@test:/$ bower search dynatable
Search results:
dynatable git://github.com/JangoSteve/jquery-dynatable.git
```

but following is empty:

http://bower.io/search/?q=dynatable

**Comment by crissdev** [comment]
`http://bower.io/search/?q=knockout-validation` also shows no results :disappointed: and the package has been recently updated.

**Comment by cvn** [comment]
@crissdev That URL seems to be returning results now, not sure if they're the ones you're looking for.

My package and @sheerun's are still nowhere to be found. Kind of a bummer.

**Comment by crissdev** [comment]
@cvn yeah, that's the real problem - it's not returning what it should. Have you tried to remove it from Bower and add it again?

**Comment by cvn** [comment]
@crissdev No. I have not.

**Comment by crissdev** [comment]
@sindresorhus Is there any way we can make our packages show up in bower search page? Thanks.

**Comment by davidjbradshaw** [comment]
@cvn @crissdev the issue seems to be that the search doesn't support packages on redirected URLs.

    github.com/jrief/angular-shims-placeholder.git

redirects to

   github.com/cvn/angular-shims-placeholder

The solution is to reregister the package on the correct URL.

**Comment by crissdev** [comment]
@davidjbradshaw Thanks. But this doesn't seem to be the issue for `knockout-validation` (bower info --verbose knockout-validation). I'm pretty sure re-registering the package will fix this issue but I would prefer not to.

**Comment by davidjbradshaw** [comment]
@crissdev in the case of `knockout-validation` the issue is that `ko-validation` was registered with the same URL later, so the dedupe in the search results show that. 

See: bower/search/pull/47 for details and then update `bower/search/blob/gh-pages/js/config/whitelist.js` to force the search to display the correct entry.

**Comment by crissdev** [comment]
Thanks @davidjbradshaw. I've created a PR to whitelist `knockout-validation` #61

**Comment by davidjbradshaw** [comment]
Fixed by https://github.com/bower/search-server/pull/21.

**Comment by benaston** [comment]
Hello, I have registered package "mixx" and it is still not showing the in the website search results after around an hour. It is also not showing in the results returned by the API used by webjars.org. 

Is this propogation delay of some other issue?

**Comment by desandro** [comment]
@benaston `mixx` is registered to `git://github.com/benaston/mix.git`, but either its URL is not valid, or the repo is private, so Bower cannot pull down necessary data.

**Comment by benaston** [comment]
OK many thanks. The URL had a typo in it. Thank you.

**Comment by benaston** [comment]
Sorry to trouble again. I have subsequently re registered `mixx` with Bower, but it still will not show in the Bower search engine. It should be registered against the public repo `git://github.com/benaston/mixx.git`. Note the two xx's on `mixx`.

**Comment by desandro** [comment]
Looks like the previous un-registration didn't work, most likely because the URL was bad. I had to go in and manually delete it. I've re-registered it to `git://github.com/benaston/mixx.git`. It should be working now. Give it a day or so for it to show up in bower.io search results.

**Comment by benaston** [comment]
Thank you.
